### ISSUE TITLE
the finalAnnots.mat

### ISSUE THREAD

**Issue by kikyou123** [gurkirt/corrected-UCF101-Annots#1]
how can i load the finalAnnots.mat， I find the annots image is less than the frames in a video, for example the Basketball/v_Basketball_g01_c01 video have 141 frames, but you give only 44 annots？

**Comment by gurkirt** [comment]
There are only 44 frames in which action is happening so ground truth exists only for those. It is a temporally trimmed dataset. Each annotation has start and end frame as well end_frame-start_frame + 1 == number_of_bounidng_box annotations.

**Comment by kikyou123** [comment]
Thanks very much! But I notice there are some annot like 
![00106](https://user-images.githubusercontent.com/19486038/33117436-6d769ae8-cfa3-11e7-92b5-22c33faf548b.jpg)
Is it normal?

**Comment by gurkirt** [comment]
Just check if you have offset it with start frame of the tube. Each tube has start frame num 'sf' or .sf field in Matlab. Girst box of the tube doesn't mean the first frame of the video. It means start frame of the tube.
