### ISSUE TITLE
Provided pyannot.pkl file doesnt seem to have all test files

### ISSUE THREAD

**Issue by pedro-abreu** [gurkirt/corrected-UCF101-Annots#5]
There are 914 test samples in the test split (present in all other evaluations). Yet after loading pyannot.pkl only 846 of these seemed to exist in the file.

**Comment by gurkirt** [comment]
Can you elaborate a little more about other evaluation? If I remember correctly, there should be 910 test videos with annotations. We need to remove 4 because the annotations there were really messed-up.

**Comment by pedro-abreu** [comment]
So the 910 videos in testsplit.mat are not the in the 914 videos in testsplit01.txt? All the .mat files for the results of other evaluations (peng, saha, etc) have 914 entries.

**Comment by gurkirt** [comment]
I still don't get what are you trying to say. 
914 is a superset of 910.

**Comment by pedro-abreu** [comment]
Oh ok I get it, sorry. Thanks :)!

**Comment by gurkirt** [comment]
Great!
Good luck with your work!
