### ISSUE TITLE
corrected-UCF101-Annots can not be downloaded 

### ISSUE THREAD

**Issue by wxz0918** [gurkirt/corrected-UCF101-Annots#8]
hello, corrected-UCF101-Annots can not be downloaded, could you send it to wangxuzhi@tju.edu.cn or upload it again? thank you very much

**Comment by gurkirt** [comment]
It still works for me. What do you mean can't be downloaded? Which file are you trying to download? Link, please?

**Comment by wxz0918** [comment]
hello I can not download file pyannot.pkl. Could you sent to wangxuzhi@tju.edu.cn. Thank you very much.



---Original---

**Comment by gurkirt** [comment]
Sorry, it is fully accessible. I am not sure what is the problem you are facing. here is the link, https://github.com/gurkirt/corrected-UCF101-Annots/raw/master/pyannot.pkl
